# Basic
title: Welcome
subtitle: Yan Feng's blog
email: fy2462@gmail.com
welcome_message: <a href="#" target="_blank"></a>
description:
creator: <a href="https://fy2462.github.io">@fy2462</a>

url: "https://fy2462.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/fy2462'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: fy2462
    # duoshuo: 
    
# Social
social:
    github: fy2462
    mail: fy2462@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

sass:
  style: compressed

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: true
    block:
      line_numbers: false
      start_line: 1
